/**
 * Countries that return meals from `filter.php?a=<country>`.
 *
 * TheMealDB's `list.php?a=list` returns 195 cuisines, but 132 of them have no
 * meals yet, so the Cuisines screen only shows these. Checking at runtime
 * would take ~195 requests and hit the API's rate limit.
 *
 * Last checked against the free API on 2026-09-30.
 */
export const COUNTRIES_WITH_MEALS: ReadonlySet<string> = new Set([
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Belgium",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Canada",
  "Cayman Islands",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Denmark",
  "Dominica",
  "Egypt",
  "Estonia",
  "France",
  "Greece",
  "India",
  "Ireland",
  "Italy",
  "Jamaica",
  "Japan",
  "Kenya",
  "Laos",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Netherlands",
  "Norway",
  "Philippines",
  "Poland",
  "Portugal",
  "Russia",
  "Saudi Arabia",
  "Slovakia",
  "Spain",
  "Syria",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Venezuela",
  "Vietnam",
]);
